### ISSUE TITLE
Confusing course material | Chapter 3 Exercise 5

### ISSUE THREAD

**Issue by Hadrien-lcrx** [datacamp/courses-intro-to-unix-shell#112]
In [How do I restore an old version of a file?](https://campus.datacamp.com/courses/introduction-to-git-for-data-science/undo?ex=5), the logs feature different comments and hashes, but they all have the exact same date. It makes it less easy to distinguish between them.

### Suggestion
Update the logs to give them different times and dates.

### Screenshot
![image](https://user-images.githubusercontent.com/22552805/35374973-7b196dc2-01a5-11e8-991a-0af5d2c80d02.png)

Cf gh@pyrocortex.com, #83206
Cc @bakera81

**Comment by Hadrien-lcrx** [comment]
@gvwilson would you have access to ZenHub to move the issue? Otherwise, maybe we should tag Yashas?

**Comment by filipsch** [comment]
Issue moved to [datacamp/courses-intro-to-git #45](https://github.com/datacamp/courses-intro-to-git/issues/45) via [**ZenHub**](https://www.zenhub.com/)
