### ISSUE TITLE
Different answers deemed correct | Chapter 4 Exercise 8

### ISSUE THREAD

**Issue by Hadrien-lcrx** [datacamp/courses-intro-to-unix-shell#113]
In [How can I merge two branches with conflicts?](https://campus.datacamp.com/courses/introduction-to-git-for-data-science/working-with-branches?ex=8), different commands for the first and last instructions are deemed correct.

### Suggestions
Update the commands, hints and grader if this isn't expected behavior.

### First instructions
"You are in the `master` branch of the `dental` repository. Merge the changes from the `alter-report-title` branch (the source) into the `master` branch (the destination)."

#### Solution code
```shell
git merge --no-edit -m "Merging altered report title" alter-report-title master
```

#### Alternative code
```shell
git merge alter-report-title master
```

### Last instructions
"Commit your changes with a log message."

#### Solution code
```shell
git commit -m "Reconciling"
```

#### Alternative code (throws an error but passed the grader)
```shell
git commit -m 'resolved conflict' report.txt
```

#### Solution code
![image](https://user-images.githubusercontent.com/22552805/35375572-ca35af36-01a7-11e8-8d7a-223d21925b3b.png)

#### Alternative code
![image](https://user-images.githubusercontent.com/22552805/35375554-bb49c070-01a7-11e8-8813-d2450424a4e1.png)

Cf gh@pyrocortex.com, #83206
Cc @bakera81

**Comment by Hadrien-lcrx** [comment]
@gvwilson would you have access to ZenHub to move the issue? Otherwise, maybe we should tag Yashas?

**Comment by filipsch** [comment]
Issue moved to [datacamp/courses-intro-to-git #44](https://github.com/datacamp/courses-intro-to-git/issues/44) via [**ZenHub**](https://www.zenhub.com/)
