### ISSUE TITLE
Exercise 5.7 | Fix Typo

### ISSUE THREAD

**Issue by ramnathv** [datacamp/courses-intro-to-unix-shell#117]
__[Exercise 5.7 | How can one shell script do many things? ](https://campus.datacamp.com/courses/5065/18217?ex=7)__ 

Over the last 8 weeks, this exercise has received __16__ feedback messages with __8__ messages received over the last week. An automatically extracted summary of the issue is provided below

> in range.sh, Total should be total

You can scan through the actual feedback messages to get more context on the. If this issue has already been addressed, please disregard it and close it. 

cc @gvwilson

<details>
  <summary>Feedback Messages</summary>
  
  <table>
 <thead>
  <tr>
   <th style="text-align:left;"> created_at </th>
   <th style="text-align:left;"> extra_info </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> 2018-03-31 13:46:54 </td>
   <td style="text-align:left;"> The original version of the range.sh file that the user is supposed to edit in the exercise contains the word 'Total'. However, the wc -l command contains the word 'total' (note the lower case 't'), so even if the user fills the placeholders correctly, his or her solution will not be taken as correct unless they also change 'Total' to 'total'. </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 2018-03-31 13:35:25 </td>
   <td style="text-align:left;"> 'Our shells scripts', which the exercise begins with, should probably read 'Our shell scripts'. </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 2018-03-31 00:16:24 </td>
   <td style="text-align:left;"> Total should not be capitalized </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 2018-03-30 19:34:07 </td>
   <td style="text-align:left;"> The base code has Total with a capital T and the solution has total with a lowercase t. </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 2018-03-29 15:19:19 </td>
   <td style="text-align:left;"> 'Total' is capitalized in the given script but needs to be lower case in the actual accepted solution.  Also, you need to make clear that the solution has to be opened in the command shell under solutions. </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 2018-03-28 10:36:06 </td>
   <td style="text-align:left;"> In the previous task, the given word "Total" should be replaced by "total" </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 2018-03-26 19:43:32 </td>
   <td style="text-align:left;"> range.sh has "Total" instead of "total", but the instructions do not indicate that the existing code should be altered, only the blanks. The feedback for wrong answers is extremely unhelpful when the edited file is not what it expects and it took a bit of troubleshooting to find this error. </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 2018-03-26 14:41:40 </td>
   <td style="text-align:left;"> in range.sh, Total should be total </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 2018-03-24 15:39:22 </td>
   <td style="text-align:left;"> not "Total" but only "total" </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 2018-03-18 20:35:06 </td>
   <td style="text-align:left;"> In step \#1, range.sh  initially contains the following: "wc - l ____ | grep ____ Total"

The word "Total" should not be capitalized and the user needs to lowercase it to get the code to work. </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 2018-03-18 11:42:25 </td>
   <td style="text-align:left;"> Within the range.sh file the word "Total" is written with the uppercase hence the solution is not working properly until the lowercase is used </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 2018-03-08 22:11:22 </td>
   <td style="text-align:left;"> should be a "total", not a "Total". "total" is in an output of wc -l !!!!!!! </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 2018-02-26 13:38:21 </td>
   <td style="text-align:left;"> the 'Total' in the range.sh script should have a lower case, or the one in the solution should have a uppercase </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 2018-02-16 17:57:58 </td>
   <td style="text-align:left;"> in range.sh, "Total" is spelled with a capital T by default. grep -v Total will not eliminate the line with the total in it because total is spelled with lower case "t." However, the instructions say to only modify the "___" text. </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 2018-02-13 13:24:28 </td>
   <td style="text-align:left;"> The file range.sh contains word "Total" with capital letter, while the course expects "total" as the correct answer (as in range-1.sh). </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 2018-02-06 12:02:56 </td>
   <td style="text-align:left;"> Total should be total without capital </td>
  </tr>
</tbody>
</table>
  
</details>

**Comment by filipsch** [comment]
Was already fixed
