### ISSUE TITLE
Cannot silently set a shell variable

### ISSUE THREAD

**Issue by gvwilson** [datacamp/courses-intro-to-unix-shell#132]
Chapter 4 has a two-part exercise in which the first step is:

```
testing=seasonal/winter.csv
```

and the second is supposed to be:

```
head -n 1 $testing
```

However, to get the solution to pass, we have to include *both* lines in the solution for the second part.

**Comment by filipsch** [comment]
Minor issue that shouldn't be addressed IMO.
