### ISSUE TITLE
3.11 | How can I stop a running program?

### ISSUE THREAD

**Issue by sumedh10** [datacamp/courses-intro-to-unix-shell#140]
https://www.datacamp.com/teach/edit/repositories/1395/branches/ch03-2018-05 

Students don't get the chance to use `CTRL-C` since as soon as they follow the instruction and run `head -n 1 seasonal/winter.csv > winter.txt | grep -v Tooth`, the SCT passes and the exercise completion screen is shown.

**Comment by gvwilson** [comment]
Fixed in d8e94f9b2cf - please confirm.
