### ISSUE TITLE
Review updated solutions

### ISSUE THREAD

**Issue by sumedh10** [datacamp/courses-intro-to-unix-shell#141]
In Ch5 branch: 

https://github.com/datacamp/courses-intro-to-unix-shell/tree/ch05-2018-05 

https://www.datacamp.com/teach/repositories/1395/branches/ch05-2018-05 

I updated solutions to 2 sub-exercises which had extra code (redundant, as far as I can tell). The exercises work fine and the build passes. Still it would be good if you can review the commits before I merge it into master

- [does 5-5 still work?](https://github.com/datacamp/courses-intro-to-unix-shell/commit/0c7187da4663eb20585299ae82bc7984372c5c94) (this should close #133 )
- [does 5-7 still work?](https://github.com/datacamp/courses-intro-to-unix-shell/commit/b5bfa18a0c4cccb03c341142cd52b61e44ad112e)

**Comment by gvwilson** [comment]
Thanks - the exercise keeps the previous state of the shell, so if the user did the right thing, we can chain like this. (I was copying in a solution file because I wasn't sure they would do the right thing each time.)
