### ISSUE TITLE
The correct answer is not accepted

### ISSUE THREAD

**Issue by sylarbui** [datacamp/courses-intro-to-unix-shell#144]
## Summary of the issue

The correct answer is not accepted in the 5th part of the exercise 10

![2018-07-22_12h07_30](https://user-images.githubusercontent.com/40219472/43118584-b073632c-8f3c-11e8-8ebb-1b0e7061f9df.png)
![2018-07-23_10h05_36](https://user-images.githubusercontent.com/40219472/43118585-b09faaa4-8f3c-11e8-8c4c-267adbeaf1bd.png)

Course: Introduction to shell for data science

Exercise link: https://campus.datacamp.com/courses/introduction-to-git-for-data-science/basic-workflow?ex=10

## Additional information
User ID: 2591667

For support: https://datacamp.zendesk.com/agent/tickets/108138

<div style="background-color:#BBDEFB;padding:10px;border-radius:5px;" id="zdArea">                             	                                                              <div style="text-decoration:underline;margin-bottom:5px;color:#00000082;" id="zd-ReservedAreaHeader">                 <span class="zdDescription" style="font-weight: bold;"><h3 style="margin:0px;padding:0px;">Zendesk Information</h3></span>                 <div class="zdValue"></div>             </div>                          <div class="ValueTypeField" style id="zd-SupportCount"><span style="margin-right:5px;">&#9679;</span>                 <span class="zdDescription" style="font-weight: bold;">Total Number of additional reports:</span>                 <span class="zdValue">6</span>             </div>             </div>

**Comment by sylarbui** [comment]
@gvwilson Could you take a look a this? We already have 6 reports about this issue.

**Comment by gvwilson** [comment]
I am no longer with DataCamp (I was terminated in June).

**Comment by klmedeiros** [comment]
@sylarbui The exercise you link up there is intro to Git but this is on the intro to shell repo. Which course is the issue here?

**Comment by filipsch** [comment]
I checked, and in the `fs-refactor` branch this also works.
