### ISSUE TITLE
Correct answer is not accepted | Chapter 5 ex=7

### ISSUE THREAD

**Issue by kasthynguyen** [datacamp/courses-intro-to-unix-shell#148]
Link to error: [How can one shell script do many things?](https://campus.datacamp.com/courses/introduction-to-shell-for-data-science/creating-new-tools?ex=7)

INSTRUCTIONS 3/4: The answer is correct, but it's not accepted. 

Add a second line to range.sh to print the name and record count of the longest file in the directory as well as the shortest. This line should be a duplicate of the one you have already written, but with sort -n -r rather than sort -n.

wc -1 $@ | grep -v total | sort -n | head -n 1
wc -1 $@ | grep -v total | sort -n -r | head -n 1

![error](https://user-images.githubusercontent.com/23623241/44083529-67d880d6-9fde-11e8-9a0d-4dcc3517addf.png)

![ezgif-2-1a3f5a275a](https://user-images.githubusercontent.com/23623241/44084028-d304d764-9fdf-11e8-8f11-dcc9e93bbcdf.gif)

cc @Robert-cabral @sylarbui @MelRemy

**Comment by Jinmyung98** [comment]
I ran into the same issue and solved it by adding a blank space between two lines.
