### ISSUE TITLE
Find a way to suppress extra echo and cat commands

### ISSUE THREAD

**Issue by gvwilson** [datacamp/courses-intro-to-unix-shell#93]
We sometimes have to pad solutions with `echo` or `cat` to prevent the shell from getting stuck, but when learners display solutions, those extra commands confuse them.  Similarly, when we want the user to use `nano`, we have to use `cp` or something like it to create the file. We've documented this by adding comments to solutions, but it's still generating a lot of complaints.

**Comment by filipsch** [comment]
It's reported on learn-features, so closing here.
